# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
# ---------------
# make a fibonacci sequence of indeterminate length
fib_sequence = [1,2]
while fib_sequence.length < 10
  fib_sequence << (fib_sequence[fib_sequence.length - 2] + fib_sequence[fib_sequence.length - 1])
end

p fib_sequence

# stop making the sequence before the last value in the array is greater the 4000000
# take all the values and get rid of all the odd ones
# take all the even values and add them up
